//array fo the sites
let siteArray = [{
        number: 1,
        name: "Black Heritage Trail of New Hampshire office",
        address: "222 Court Street",
        latitude: 43.07522,
        longitude: -70.7571,
        comment: "",
        descriptivePlaque: false,
        orginalExists: true,
    },
    {
        number: 2,
        name: "Governor John Langdon House",
        address: "143 Pleasant Street",
        latitude: 43.07517,
        longitude: -70.756,
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 3,
        name: "William Pitt Tavern",
        address: "416 Court St.",
        latitude: 43.074893,
        longitude: -70.760220,
        comment: "Strawbery Banke Museum",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 4,
        name: "Docks and view of Portsmouth Naval Shipyard",
        address: "Prescott Park",
        latitude: 43.074893,
        longitude: -70.760220,
        comment: "",
        descriptivePlaque: false,
        orginalExists: false,
    },
    {
        number: 5,
        name: "Sherburne House",
        address: "Strawbery Banke campus",
        latitude: 43.,
        longitude: -70.,
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 6,
        name: "South Meeting House",
        address: "280 Marcy Street",
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 7,
        name: "NH Gazette",
        address: "corner of Howard and Washington Streets",
        comment: "private",
        descriptivePlaque: true,
        orginalExists: false,
    },
    {
        number: 8,
        name: "Cooper House and Beauty Shop",
        address: "171 Washington Street",
        comment: "private",
        descriptivePlaque: false,
        orginalExists: true,
    },
    {
        number: 9,
        name: "Stoodley’s Tavern",
        address: "14 Hancock Street",
        comment: "Strawbery Banke Museum",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 10,
        name: "Penhallow House",
        address: "93 Washington Street",
        comment: "Strawbery Banke Museum",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 11,
        name: "Warner House",
        address: "150 Daniel Street",
        comment: "",
        descriptivePlaque: false,
        orginalExists: true,
    },
    {
        number: 12,
        name: "Saint John’s Church",
        address: "100 Chapel Street",
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 13,
        name: "Waterfront",
        address: "Ceres Street",
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 14,
        name: "Moffatt-Ladd House",
        address: "154 Market Street",
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 15,
        name: "Black Whipple House",
        address: "127 High Street",
        comment: "private",
        descriptivePlaque: true,
        orginalExists: false,
    },
    {
        number: 16,
        name: "Meeting Rooms",
        address: "14-16 Market Square",
        comments: "corner of Daniel and Pleasant Streets",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 17,
        name: "Town Pump and Stocks",
        address: "next to North Church",
        comment: "",
        descriptivePlaque: false,
        orginalExists: false,
    },
    {
        number: 18,
        name: "North Church",
        address: "Market Square",
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 19,
        name: "Pomp and Candace Spring House and Bakery",
        address: "Church Street",
        comment: "",
        descriptivePlaque: false,
        orginalExists: false,
    },
    {
        number: 20,
        Name: "The Music Hall (The Temple )",
        address: "Chestnut Street at Congress Street",
        comment: "",
        descriptivePlaque: true,
        orginalExists: false,
    },
    {
        number: 21,
        name: "John Paul Jones House",
        address: "43 Middle Street",
        comment: "",
        descriptivePlaque: false,
        orginalExists: true,
    },
    {
        number: 22,
        name: "Rockingham House",
        address: "401 State Street",
        comment: "private",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 23,
        name: "African Burying Ground",
        address: "Chestnut Street",
        comment: "between Court & State Streets",
        descriptivePlaque: true,
        orginalExists: true,
    },
    {
        number: 24,
        name: "South Church",
        address: "292 State Street",
        comment: "",
        descriptivePlaque: true,
        orginalExists: true,
    }
]